version: '3'
services:
  nginx:
    build:
      context: ./nginx-docker
    container_name: zem-nginx
    ports:
      - 1935:1935
      - 7965:7965
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
  zem:
    build:
      context: .
    container_name: zem
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
